group: edge
language: java
jdk: oraclejdk8
install: true
script:
  - >
    for version in 4.0 4.0.1 4.0.2; do
      gradle wrapper --gradle-version $version --distribution-type=all;
      bash gradlew -v;
      bash gradlew clean check license build install publish asciidoctor -S;
      bash gradlew --stop;
    done;
before_cache:
  - bash gradlew dependencyUpdates -Drevision=release
  - bash gradlew --stop
  - rm -rf $HOME/.m2/repository/io/github/daggerok
  - rm -rf $HOME/.gradle/caches/modules-2/files-2.1/gradle.plugin*
  - rm -rf $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.m2/
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
